/* =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */
/*  »Project«   Teikitu Gaming System (TgS) (∂)
    »File«      TgS Common - Geometry 3D - Triangle [Collision].c
    »Author«    Andrew Aye (mailto: teikitu@andrewaye.com, https://www.andrew.aye.page)
    »Version«   5.17 | »GUID« 3ED3C595-046B-47FB-8785-5C167178CD24 */
/*  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ */
/*  Copyright: © 2002-2023, Andrew Aye.  All Rights Reserved.
    This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. To view a copy of this license,
    visit http://creativecommons.org/licenses/by-nc-sa/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA. */
/* =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */
#if defined (TGS_COMMON_GEOMETRY_H)

#if !defined (TEMPLATE_TYPE_EXPANSION__RELOAD)
    #define TEMPLATE_TYPE_EXPANSION__RELOAD

    #if TgCOMPILE__NON_NATIVE_VECTOR_AS_NATIVE
        #define TEMPLATE__VECTOR_DIM 4
        #define TEMPLATE__TYPE_SIZE 64
        #include __FILE__
    #endif

    #define TEMPLATE__VECTOR_DIM 4
    #define TEMPLATE__TYPE_SIZE 32

    #undef TEMPLATE_TYPE_EXPANSION__RELOAD
#endif

#include "TgS COMMON/TgS Common - Base - Defines [Template] [Math].h_inc"

/* == Common ===================================================================================================================================================================== */

/* ---- FCN_VO(tgGM_CT_Is_Point_Culled) ------------------------------------------------------------------------------------------------------------------------------------------ */
/* ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
TgBOOL FCN_VO(tgGM_CT_Is_Point_Culled)( VEC_OBJ_T(TgCTRI,CPCU) psCT1, VEC_T(1,C) vT0, VEC_T(1,C) vT1 )
{
    /*  Check the barycentric co-ordinates for this point against the validity of the triangle's features.  If its within a margin of error of an ignored feature */
    /* (vertex, edge) then return the point as invalid. */

    /* Edge generated by vertex 0 and vertex 1 */
    if (!FCN_VO(tgGM_CT_Test_Edge_0)( psCT1 ) && FCN_V(tgMH_Is_NR0)( vT1 ))
    {
        if (FCN_VO(tgGM_CT_Test_Point_0)( psCT1 ) && FCN_V(tgMH_Is_NR0)( vT0 ))
        {
            return (true);
        }

        if (FCN_VO(tgGM_CT_Test_Point_1)( psCT1 ) && FCN_V(tgMH_Is_NR0)( FCN_V(tgMH_SUB)( vT0, FCN_V(tgMH_SET1)( TYPE_K(1) ) ) ))
        {
            return (true);
        }

        return (false);
    }

    /* Edge generated by vertex 0 and vertex 2 */
    if (!FCN_VO(tgGM_CT_Test_Edge_2)( psCT1 ) && FCN_V(tgMH_Is_NR0)( vT0 ))
    {
        if (FCN_VO(tgGM_CT_Test_Point_0)( psCT1 ) && FCN_V(tgMH_Is_NR0)( vT1 ))
        {
            return (true);
        }

        if (FCN_VO(tgGM_CT_Test_Point_2)( psCT1 ) && FCN_V(tgMH_Is_NR0)( FCN_V(tgMH_SUB)( vT1, FCN_V(tgMH_SET1)( TYPE_K(1) ) ) ))
        {
            return (true);
        }

        return (false);
    }

    /* Edge generated by vertex 1 and vertex 2 */
    if (!FCN_VO(tgGM_CT_Test_Edge_1)( psCT1 ) && FCN_V(tgMH_Is_NR0)( FCN_V(tgMH_SUB)( FCN_V(tgMH_ADD)( vT0, vT1 ), FCN_V(tgMH_SET1)( TYPE_K(1) ) ) ))
    {
        if (FCN_VO(tgGM_CT_Test_Point_1)( psCT1 ) && FCN_V(tgMH_Is_NR0)( vT1 ))
        {
            return (true);
        }

        if (FCN_VO(tgGM_CT_Test_Point_2)( psCT1 ) && FCN_V(tgMH_Is_NR0)( vT0 ))
        {
            return (true);
        }

        return (false);
    }

    return (true);
}


/* =============================================================================================================================================================================== */

#include "TgS COMMON/TgS Common - Base - Defines [Template] [Math].h_inc"

/*# defined (TGS_COMMON_GEOMETRY_H) */
#endif
