# 015482FC-A4BD-4E1C-AE49-A30E5728D73A
CMAKE_MINIMUM_REQUIRED(VERSION 3.17)
CMAKE_POLICY(VERSION 3.17)


# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ #
# SETUP

MESSAGE(STATUS "")
MESSAGE(STATUS "")
MESSAGE(STATUS "DEBUG PROJECT NAME: ${_CMAKE_PROJECT_NAME} / ${MK_PROJECT_NAME}")
MESSAGE(STATUS "")
MESSAGE(STATUS "PROJECT IDE: ${MK_IDE_NAME}")
MESSAGE(STATUS "COMPILER (BUILD): ${MK_COMPILER_NAME} ${MK_COMPILER_FRONTEND_NAME} [C:${CMAKE_C_COMPILER_ID}, CXX: ${CMAKE_CXX_COMPILER_ID}]")
MESSAGE(STATUS "TARGET: ${MK_COMPILE__TYPE}")
MESSAGE(STATUS "HARDWARE: ${MK_HARDWARE_NAME}")
MESSAGE(STATUS "THREAD: ${MK_BUILD__THREAD_NAME}")
MESSAGE(STATUS "UNIVERSAL: ${MK_BUILD__UNIVERSAL_NAME}")
MESSAGE(STATUS "OS: ${MK_BUILD__OS_NAME}")
MESSAGE(STATUS "DEVICE: ${MK_BUILD__DEVICE_NAME}")
IF (MK_COMPILE_PLATFORM_TEXT__WIDE)
    MESSAGE(STATUS "PLATFORM TEXT: WIDE")
ELSE ()
    MESSAGE(STATUS "PLATFORM TEXT: UTF8")
ENDIF ()
MESSAGE(STATUS "FEATURE (GRAPHICS): ${MK_BUILD__GRAPHICS_NAME}")
MESSAGE(STATUS "FEATURE (AUDIO): ${MK_BUILD__AUDIO_NAME}")
MESSAGE(STATUS "")
MESSAGE(STATUS "")



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ #
# COMPILE FLAGS

MESSAGE(VERBOSE "COMPILE FLAGS (C): ${CMAKE_C_FLAGS}")
MESSAGE(VERBOSE "")
MESSAGE(VERBOSE "")
MESSAGE(VERBOSE "COMPILE FLAGS (C++): ${CMAKE_CXX_FLAGS}")
MESSAGE(VERBOSE "")
MESSAGE(VERBOSE "")
