name: Debug
on:
  push:
  workflow_dispatch:

env:
  BUILD_URL: "https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git"

defaults:
  run:
    shell: powershell
    working-directory: build_scripts

jobs:
  tagcheck:
    name: check tag
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: .\windows_cmake_command.ps1 -VERBOSE -CICD_BUILD -TEIKITU -IDE:NINJA -COMPILER:CLANG -THREAD:WIN -OS:WIN -DEVICE:DESKTOP -CPU:C17_X64 -GPU:DX12 -BUILD_TYPE:DEBUG
  
