name: Debug
on:
  push:
  workflow_dispatch:

env:
  BUILD_URL: "https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git"

defaults:
  run:
    shell: bash
    working-directory: ./build_scripts

jobs:
  tagcheck:
    name: Debug Linux X64 None
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Install Software
        run: |
          git config --global user.email "andrew.aye@gmail.com"
          git config --global user.name "Andrew Aye"

      - name: Build Teikitu
        run: bash bash_cmake_commands.sh --VERBOSE --CICD_BUILD --TEIKITU --IDE UNIX --COMPILER CLANG --THREAD POSIX --OS POSIX --DEVICE DESKTOP --CPU C17_X64 --GPU NONE --BUILD_TYPE DEBUG
